export const CURRENCY_CHANGE_BASE = 'CURRENCY_CHANGE_BASE';
export const CURRENCY_GET_INITIAL_CONVERSION_RATES = 'CURRENCY_GET_INITIAL_CONVERSION_RATES';
export const CURRENCY_QUOTE_CURRENCY_ADD = 'CURRENCY_ADD_QUOTE_CURRENCY';
export const CURRENCY_QUOTE_CURRENCY_REMOVE = 'CURRENCY_REMOVE_QUOTE_CURRENCY';

export const CURRENCY_MARK_CURRENCY_AS_FAVORITE = 'CURRENCY_MARK_CURRENCY_AS_FAVORITE';
export const CURRENCY_UNMARK_CURRENCY_FROM_FAVORITES = 'CURRENCY_UNMARK_CURRENCY_FROM_FAVORITES';

export const CURRENCY_CONVERSION_RATES_FETCH_SUCCESS = 'CURRENCY_CONVERSION_RATES_FETCH_SUCCESS';
export const CURRENCY_CONVERSION_RATES_FETCH_FAILURE = 'CURRENCY_CONVERSION_RATES_FETCH_FAILURE';
